"""Unit tests for the SQLite->Postgres translation helpers (webapp/pgcompat.py).

Pure functions — no database required, so these always run (unlike the live
parity suite in test_postgres_backend.py, which is gated on a Postgres URL)."""

import re

from webapp import db
from webapp.pgcompat import (
    _split_statements,
    sqlite_schema_to_postgres,
    translate_query,
)


def test_positional_placeholders_become_percent_s():
    sql, params = translate_query("SELECT * FROM t WHERE a = ? AND b = ?", (1, 2))
    assert sql == "SELECT * FROM t WHERE a = %s AND b = %s"
    assert params == [1, 2]


def test_named_placeholders_become_percent_named():
    sql, params = translate_query(
        "INSERT INTO t (a, b) VALUES (:a, :b)", {"a": 1, "b": 2})
    assert sql == "INSERT INTO t (a, b) VALUES (%(a)s, %(b)s)"
    assert params == {"a": 1, "b": 2}


def test_no_params_passes_through_untouched():
    sql, params = translate_query("SELECT 1", ())
    assert sql == "SELECT 1"
    assert params is None


def test_literal_percent_doubled_when_params_present():
    # A stray literal % must be doubled, else psycopg reads it as a placeholder.
    sql, params = translate_query(
        "SELECT * FROM t WHERE a LIKE '%x%' AND b = ?", ("y",))
    assert sql == "SELECT * FROM t WHERE a LIKE '%%x%%' AND b = %s"
    assert params == ["y"]


def test_schema_transform_swaps_pk_and_real():
    pg = sqlite_schema_to_postgres(db.SCHEMA)
    # SQLite implicit-rowid PKs become explicit IDENTITY columns.
    assert "INTEGER PRIMARY KEY" not in pg
    assert pg.count("GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY") == db.SCHEMA.count("INTEGER PRIMARY KEY")
    # Every REAL column becomes DOUBLE PRECISION; no bare REAL type survives.
    assert not re.search(r"\bREAL\b", pg)
    assert re.search(r"fit_score\s+DOUBLE PRECISION", pg)
    # A TEXT primary key (prep_meta) is deliberately left untouched.
    assert "key        TEXT PRIMARY KEY" in pg


def test_schema_transform_preserves_table_and_index_count():
    pg = sqlite_schema_to_postgres(db.SCHEMA)
    assert pg.count("CREATE TABLE") == db.SCHEMA.count("CREATE TABLE")
    assert pg.count("CREATE INDEX") == db.SCHEMA.count("CREATE INDEX")


def test_split_statements_drops_comment_only_chunks():
    script = """
    -- a leading comment
    CREATE TABLE a (id INTEGER);
    -- a standalone comment block
    CREATE TABLE b (id INTEGER);
    """
    stmts = _split_statements(script)
    assert len(stmts) == 2
    assert all("CREATE TABLE" in s for s in stmts)
