"""CtCI book problems — full prompt/hints/solution per problem.

Source of truth: the per-chapter JSON files produced by the
`extract-ctci-problems` workflow in `data/prep_sources/modules/`. Those
JSONs are generated by reading the OCR'd CtCI 6e text in
`data/prep_sources/chapters/ctci_chNN_*.txt` (cleaned via LLM extraction).

This module reads those JSONs at import time and exposes
``CTCI_PROBLEMS_BY_MODULE`` — a dict keyed by module slug (matching
``TRACK_CODING['modules']`` slugs) whose values are problem dicts shaped
exactly the way `seed.seed_into_db()` expects under each module's
``ctci_problems`` key.
"""

from __future__ import annotations

import json
from pathlib import Path

# data/prep_sources/modules/ relative to repo root. Resolves against CWD at
# runtime since the app is launched from the repo root.
_MODULE_JSON_DIR = Path("data/prep_sources/modules")

# Slugs in the per-chapter JSONs are CtCI's chapter slugs. Some `TRACK_CODING`
# modules use longer/scoped slugs. Map the JSON slug → the TRACK_CODING slug
# so the attachment in coding.py finds the right module.
_SLUG_ALIASES = {
    "system-design": "ctci-system-design-intro",
    "moderate": "ctci-moderate",
    "hard": "ctci-hard",
}


def _load_chapter_problems() -> dict[str, list[dict]]:
    by_module: dict[str, list[dict]] = {}
    if not _MODULE_JSON_DIR.is_dir():
        return by_module
    for path in sorted(_MODULE_JSON_DIR.glob("coding__ctci-ch-*.json")):
        try:
            data = json.loads(path.read_text())
        except (ValueError, OSError):
            continue
        slug = data.get("module_slug")
        problems = data.get("problems") or []
        if not slug or not problems:
            continue
        slug = _SLUG_ALIASES.get(slug, slug)
        by_module[slug] = [_normalize(p) for p in problems if _valid(p)]
    return by_module


def _valid(p: dict) -> bool:
    return bool(p.get("ctci_id") and p.get("slug") and p.get("title")
                and p.get("prompt_md") and p.get("solution_md"))


def _normalize(p: dict) -> dict:
    return {
        "ctci_id": p["ctci_id"],
        "slug": p["slug"],
        "title": p["title"],
        "prompt_md": p["prompt_md"],
        "examples_md": p.get("examples_md", "") or "",
        "hints": list(p.get("hints") or []),
        "solution_md": p["solution_md"],
        "complexity": p.get("complexity", "") or "",
    }


CTCI_PROBLEMS_BY_MODULE: dict[str, list[dict]] = _load_chapter_problems()
