"""Curated, bundled "what does this company ask?" LeetCode sets.

Each list is ordered **most-commonly-asked first** (hand-ranked from the
well-known company tags / community frequency datasets). Entries are
``{"n": leetcode_number, "slug": url_slug, "title": ..., "diff": easy|medium|hard,
"topics": ...}``. A few perennial favourites are LeetCode-premium-locked
(noted in ``topics``); they're kept because they show up constantly in
company question lists even though the problem page needs a subscription.

This is a starting point, not gospel — the in-app **⟳ Refresh questions**
button pulls a larger, frequency-measured list from the community dataset
configured in ``config/settings.yaml`` and overlays it on top.
"""

from __future__ import annotations

COMPANY_QUESTIONS: dict[str, list[dict]] = {
    "Amazon": [
        {"n": 1, "slug": "two-sum", "title": "Two Sum", "diff": "easy", "topics": "Array, Hash Table"},
        {"n": 146, "slug": "lru-cache", "title": "LRU Cache", "diff": "medium", "topics": "Design, Hash Table"},
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph, BFS/DFS"},
        {"n": 937, "slug": "reorder-data-in-log-files", "title": "Reorder Data in Log Files", "diff": "easy", "topics": "Sorting, String"},
        {"n": 973, "slug": "k-closest-points-to-origin", "title": "K Closest Points to Origin", "diff": "medium", "topics": "Heap"},
        {"n": 21, "slug": "merge-two-sorted-lists", "title": "Merge Two Sorted Lists", "diff": "easy", "topics": "Linked List"},
        {"n": 23, "slug": "merge-k-sorted-lists", "title": "Merge k Sorted Lists", "diff": "hard", "topics": "Heap, Linked List"},
        {"n": 5, "slug": "longest-palindromic-substring", "title": "Longest Palindromic Substring", "diff": "medium", "topics": "DP, String"},
        {"n": 763, "slug": "partition-labels", "title": "Partition Labels", "diff": "medium", "topics": "Greedy, Two Pointers"},
        {"n": 819, "slug": "most-common-word", "title": "Most Common Word", "diff": "easy", "topics": "String, Hash Table"},
        {"n": 1152, "slug": "analyze-user-website-visit-pattern", "title": "Analyze User Website Visit Pattern", "diff": "medium", "topics": "Hash Table (premium)"},
        {"n": 1192, "slug": "critical-connections-in-a-network", "title": "Critical Connections in a Network", "diff": "hard", "topics": "Graph, Tarjan"},
        {"n": 994, "slug": "rotting-oranges", "title": "Rotting Oranges", "diff": "medium", "topics": "BFS, Matrix"},
        {"n": 138, "slug": "copy-list-with-random-pointer", "title": "Copy List with Random Pointer", "diff": "medium", "topics": "Linked List, Hash Table"},
        {"n": 472, "slug": "concatenated-words", "title": "Concatenated Words", "diff": "hard", "topics": "Trie, DP"},
        {"n": 957, "slug": "prison-cells-after-n-days", "title": "Prison Cells After N Days", "diff": "medium", "topics": "Simulation, Cycle"},
        {"n": 348, "slug": "design-tic-tac-toe", "title": "Design Tic-Tac-Toe", "diff": "medium", "topics": "Design (premium)"},
        {"n": 121, "slug": "best-time-to-buy-and-sell-stock", "title": "Best Time to Buy and Sell Stock", "diff": "easy", "topics": "DP, Array"},
    ],
    "Google": [
        {"n": 56, "slug": "merge-intervals", "title": "Merge Intervals", "diff": "medium", "topics": "Sorting, Intervals"},
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph, BFS/DFS"},
        {"n": 2, "slug": "add-two-numbers", "title": "Add Two Numbers", "diff": "medium", "topics": "Linked List, Math"},
        {"n": 42, "slug": "trapping-rain-water", "title": "Trapping Rain Water", "diff": "hard", "topics": "Two Pointers, Stack"},
        {"n": 84, "slug": "largest-rectangle-in-histogram", "title": "Largest Rectangle in Histogram", "diff": "hard", "topics": "Monotonic Stack"},
        {"n": 159, "slug": "longest-substring-with-at-most-two-distinct-characters", "title": "Longest Substring with At Most Two Distinct Characters", "diff": "medium", "topics": "Sliding Window (premium)"},
        {"n": 4, "slug": "median-of-two-sorted-arrays", "title": "Median of Two Sorted Arrays", "diff": "hard", "topics": "Binary Search"},
        {"n": 31, "slug": "next-permutation", "title": "Next Permutation", "diff": "medium", "topics": "Array, Two Pointers"},
        {"n": 295, "slug": "find-median-from-data-stream", "title": "Find Median from Data Stream", "diff": "hard", "topics": "Heap, Design"},
        {"n": 329, "slug": "longest-increasing-path-in-a-matrix", "title": "Longest Increasing Path in a Matrix", "diff": "hard", "topics": "DFS, Memoization"},
        {"n": 410, "slug": "split-array-largest-sum", "title": "Split Array Largest Sum", "diff": "hard", "topics": "Binary Search, DP"},
        {"n": 681, "slug": "next-closest-time", "title": "Next Closest Time", "diff": "medium", "topics": "String (premium)"},
        {"n": 359, "slug": "logger-rate-limiter", "title": "Logger Rate Limiter", "diff": "easy", "topics": "Design (premium)"},
        {"n": 388, "slug": "longest-absolute-file-path", "title": "Longest Absolute File Path", "diff": "medium", "topics": "Stack, String"},
        {"n": 904, "slug": "fruit-into-baskets", "title": "Fruit Into Baskets", "diff": "medium", "topics": "Sliding Window"},
        {"n": 482, "slug": "license-key-formatting", "title": "License Key Formatting", "diff": "easy", "topics": "String"},
        {"n": 753, "slug": "cracking-the-safe", "title": "Cracking the Safe", "diff": "hard", "topics": "Euler Circuit, DFS"},
        {"n": 843, "slug": "guess-the-word", "title": "Guess the Word", "diff": "hard", "topics": "Interactive, Minimax"},
    ],
    "Meta": [
        {"n": 1249, "slug": "minimum-remove-to-make-valid-parentheses", "title": "Minimum Remove to Make Valid Parentheses", "diff": "medium", "topics": "Stack, String"},
        {"n": 680, "slug": "valid-palindrome-ii", "title": "Valid Palindrome II", "diff": "easy", "topics": "Two Pointers"},
        {"n": 314, "slug": "binary-tree-vertical-order-traversal", "title": "Binary Tree Vertical Order Traversal", "diff": "medium", "topics": "BFS, Tree (premium)"},
        {"n": 408, "slug": "valid-word-abbreviation", "title": "Valid Word Abbreviation", "diff": "easy", "topics": "String (premium)"},
        {"n": 215, "slug": "kth-largest-element-in-an-array", "title": "Kth Largest Element in an Array", "diff": "medium", "topics": "Heap, Quickselect"},
        {"n": 236, "slug": "lowest-common-ancestor-of-a-binary-tree", "title": "Lowest Common Ancestor of a Binary Tree", "diff": "medium", "topics": "Tree, DFS"},
        {"n": 339, "slug": "nested-list-weight-sum", "title": "Nested List Weight Sum", "diff": "medium", "topics": "DFS (premium)"},
        {"n": 528, "slug": "random-pick-with-weight", "title": "Random Pick with Weight", "diff": "medium", "topics": "Prefix Sum, Binary Search"},
        {"n": 938, "slug": "range-sum-of-bst", "title": "Range Sum of BST", "diff": "easy", "topics": "Tree, DFS"},
        {"n": 227, "slug": "basic-calculator-ii", "title": "Basic Calculator II", "diff": "medium", "topics": "Stack, String"},
        {"n": 71, "slug": "simplify-path", "title": "Simplify Path", "diff": "medium", "topics": "Stack, String"},
        {"n": 199, "slug": "binary-tree-right-side-view", "title": "Binary Tree Right Side View", "diff": "medium", "topics": "BFS, Tree"},
        {"n": 273, "slug": "integer-to-english-words", "title": "Integer to English Words", "diff": "hard", "topics": "Math, String"},
        {"n": 670, "slug": "maximum-swap", "title": "Maximum Swap", "diff": "medium", "topics": "Greedy, Math"},
        {"n": 1570, "slug": "dot-product-of-two-sparse-vectors", "title": "Dot Product of Two Sparse Vectors", "diff": "medium", "topics": "Hash Table (premium)"},
        {"n": 121, "slug": "best-time-to-buy-and-sell-stock", "title": "Best Time to Buy and Sell Stock", "diff": "easy", "topics": "DP, Array"},
        {"n": 88, "slug": "merge-sorted-array", "title": "Merge Sorted Array", "diff": "easy", "topics": "Two Pointers"},
        {"n": 173, "slug": "binary-search-tree-iterator", "title": "Binary Search Tree Iterator", "diff": "medium", "topics": "Design, Tree"},
    ],
    "Apple": [
        {"n": 1, "slug": "two-sum", "title": "Two Sum", "diff": "easy", "topics": "Array, Hash Table"},
        {"n": 146, "slug": "lru-cache", "title": "LRU Cache", "diff": "medium", "topics": "Design"},
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph, BFS/DFS"},
        {"n": 4, "slug": "median-of-two-sorted-arrays", "title": "Median of Two Sorted Arrays", "diff": "hard", "topics": "Binary Search"},
        {"n": 20, "slug": "valid-parentheses", "title": "Valid Parentheses", "diff": "easy", "topics": "Stack"},
        {"n": 53, "slug": "maximum-subarray", "title": "Maximum Subarray", "diff": "medium", "topics": "DP, Kadane"},
        {"n": 121, "slug": "best-time-to-buy-and-sell-stock", "title": "Best Time to Buy and Sell Stock", "diff": "easy", "topics": "DP"},
        {"n": 42, "slug": "trapping-rain-water", "title": "Trapping Rain Water", "diff": "hard", "topics": "Two Pointers"},
        {"n": 70, "slug": "climbing-stairs", "title": "Climbing Stairs", "diff": "easy", "topics": "DP"},
        {"n": 56, "slug": "merge-intervals", "title": "Merge Intervals", "diff": "medium", "topics": "Sorting"},
        {"n": 138, "slug": "copy-list-with-random-pointer", "title": "Copy List with Random Pointer", "diff": "medium", "topics": "Linked List"},
        {"n": 3, "slug": "longest-substring-without-repeating-characters", "title": "Longest Substring Without Repeating Characters", "diff": "medium", "topics": "Sliding Window"},
        {"n": 33, "slug": "search-in-rotated-sorted-array", "title": "Search in Rotated Sorted Array", "diff": "medium", "topics": "Binary Search"},
        {"n": 215, "slug": "kth-largest-element-in-an-array", "title": "Kth Largest Element in an Array", "diff": "medium", "topics": "Heap"},
        {"n": 14, "slug": "longest-common-prefix", "title": "Longest Common Prefix", "diff": "easy", "topics": "String"},
        {"n": 23, "slug": "merge-k-sorted-lists", "title": "Merge k Sorted Lists", "diff": "hard", "topics": "Heap, Linked List"},
    ],
    "Microsoft": [
        {"n": 1, "slug": "two-sum", "title": "Two Sum", "diff": "easy", "topics": "Array, Hash Table"},
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph, BFS/DFS"},
        {"n": 206, "slug": "reverse-linked-list", "title": "Reverse Linked List", "diff": "easy", "topics": "Linked List"},
        {"n": 53, "slug": "maximum-subarray", "title": "Maximum Subarray", "diff": "medium", "topics": "DP"},
        {"n": 146, "slug": "lru-cache", "title": "LRU Cache", "diff": "medium", "topics": "Design"},
        {"n": 5, "slug": "longest-palindromic-substring", "title": "Longest Palindromic Substring", "diff": "medium", "topics": "DP, String"},
        {"n": 42, "slug": "trapping-rain-water", "title": "Trapping Rain Water", "diff": "hard", "topics": "Two Pointers"},
        {"n": 23, "slug": "merge-k-sorted-lists", "title": "Merge k Sorted Lists", "diff": "hard", "topics": "Heap"},
        {"n": 54, "slug": "spiral-matrix", "title": "Spiral Matrix", "diff": "medium", "topics": "Matrix, Simulation"},
        {"n": 273, "slug": "integer-to-english-words", "title": "Integer to English Words", "diff": "hard", "topics": "Math, String"},
        {"n": 116, "slug": "populating-next-right-pointers-in-each-node", "title": "Populating Next Right Pointers in Each Node", "diff": "medium", "topics": "Tree, BFS"},
        {"n": 138, "slug": "copy-list-with-random-pointer", "title": "Copy List with Random Pointer", "diff": "medium", "topics": "Linked List"},
        {"n": 236, "slug": "lowest-common-ancestor-of-a-binary-tree", "title": "Lowest Common Ancestor of a Binary Tree", "diff": "medium", "topics": "Tree"},
        {"n": 79, "slug": "word-search", "title": "Word Search", "diff": "medium", "topics": "Backtracking, Matrix"},
        {"n": 17, "slug": "letter-combinations-of-a-phone-number", "title": "Letter Combinations of a Phone Number", "diff": "medium", "topics": "Backtracking"},
        {"n": 994, "slug": "rotting-oranges", "title": "Rotting Oranges", "diff": "medium", "topics": "BFS, Matrix"},
    ],
    "Bloomberg": [
        {"n": 1, "slug": "two-sum", "title": "Two Sum", "diff": "easy", "topics": "Array, Hash Table"},
        {"n": 146, "slug": "lru-cache", "title": "LRU Cache", "diff": "medium", "topics": "Design"},
        {"n": 387, "slug": "first-unique-character-in-a-string", "title": "First Unique Character in a String", "diff": "easy", "topics": "Hash Table, String"},
        {"n": 50, "slug": "powx-n", "title": "Pow(x, n)", "diff": "medium", "topics": "Math, Recursion"},
        {"n": 21, "slug": "merge-two-sorted-lists", "title": "Merge Two Sorted Lists", "diff": "easy", "topics": "Linked List"},
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph"},
        {"n": 121, "slug": "best-time-to-buy-and-sell-stock", "title": "Best Time to Buy and Sell Stock", "diff": "easy", "topics": "DP"},
        {"n": 20, "slug": "valid-parentheses", "title": "Valid Parentheses", "diff": "easy", "topics": "Stack"},
        {"n": 42, "slug": "trapping-rain-water", "title": "Trapping Rain Water", "diff": "hard", "topics": "Two Pointers"},
        {"n": 692, "slug": "top-k-frequent-words", "title": "Top K Frequent Words", "diff": "medium", "topics": "Heap, Hash Table"},
        {"n": 234, "slug": "palindrome-linked-list", "title": "Palindrome Linked List", "diff": "easy", "topics": "Linked List"},
        {"n": 7, "slug": "reverse-integer", "title": "Reverse Integer", "diff": "medium", "topics": "Math"},
        {"n": 322, "slug": "coin-change", "title": "Coin Change", "diff": "medium", "topics": "DP"},
        {"n": 56, "slug": "merge-intervals", "title": "Merge Intervals", "diff": "medium", "topics": "Sorting"},
        {"n": 70, "slug": "climbing-stairs", "title": "Climbing Stairs", "diff": "easy", "topics": "DP"},
    ],
    "Uber": [
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph"},
        {"n": 380, "slug": "insert-delete-getrandom-o1", "title": "Insert Delete GetRandom O(1)", "diff": "medium", "topics": "Design, Hash Table"},
        {"n": 41, "slug": "first-missing-positive", "title": "First Missing Positive", "diff": "hard", "topics": "Array"},
        {"n": 53, "slug": "maximum-subarray", "title": "Maximum Subarray", "diff": "medium", "topics": "DP"},
        {"n": 295, "slug": "find-median-from-data-stream", "title": "Find Median from Data Stream", "diff": "hard", "topics": "Heap, Design"},
        {"n": 528, "slug": "random-pick-with-weight", "title": "Random Pick with Weight", "diff": "medium", "topics": "Prefix Sum, Binary Search"},
        {"n": 803, "slug": "bricks-falling-when-hit", "title": "Bricks Falling When Hit", "diff": "hard", "topics": "Union Find"},
        {"n": 1041, "slug": "robot-bounded-in-circle", "title": "Robot Bounded In Circle", "diff": "medium", "topics": "Simulation, Math"},
        {"n": 642, "slug": "design-search-autocomplete-system", "title": "Design Search Autocomplete System", "diff": "hard", "topics": "Trie (premium)"},
        {"n": 50, "slug": "powx-n", "title": "Pow(x, n)", "diff": "medium", "topics": "Math"},
        {"n": 64, "slug": "minimum-path-sum", "title": "Minimum Path Sum", "diff": "medium", "topics": "DP, Matrix"},
        {"n": 759, "slug": "employee-free-time", "title": "Employee Free Time", "diff": "hard", "topics": "Intervals, Heap (premium)"},
        {"n": 994, "slug": "rotting-oranges", "title": "Rotting Oranges", "diff": "medium", "topics": "BFS"},
        {"n": 207, "slug": "course-schedule", "title": "Course Schedule", "diff": "medium", "topics": "Topological Sort"},
    ],
    "Netflix": [
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph"},
        {"n": 1, "slug": "two-sum", "title": "Two Sum", "diff": "easy", "topics": "Array, Hash Table"},
        {"n": 146, "slug": "lru-cache", "title": "LRU Cache", "diff": "medium", "topics": "Design"},
        {"n": 23, "slug": "merge-k-sorted-lists", "title": "Merge k Sorted Lists", "diff": "hard", "topics": "Heap"},
        {"n": 295, "slug": "find-median-from-data-stream", "title": "Find Median from Data Stream", "diff": "hard", "topics": "Heap, Design"},
        {"n": 56, "slug": "merge-intervals", "title": "Merge Intervals", "diff": "medium", "topics": "Sorting"},
        {"n": 4, "slug": "median-of-two-sorted-arrays", "title": "Median of Two Sorted Arrays", "diff": "hard", "topics": "Binary Search"},
        {"n": 692, "slug": "top-k-frequent-words", "title": "Top K Frequent Words", "diff": "medium", "topics": "Heap"},
        {"n": 348, "slug": "design-tic-tac-toe", "title": "Design Tic-Tac-Toe", "diff": "medium", "topics": "Design (premium)"},
        {"n": 362, "slug": "design-hit-counter", "title": "Design Hit Counter", "diff": "medium", "topics": "Design (premium)"},
    ],
    "LinkedIn": [
        {"n": 68, "slug": "text-justification", "title": "Text Justification", "diff": "hard", "topics": "String, Greedy"},
        {"n": 364, "slug": "nested-list-weight-sum-ii", "title": "Nested List Weight Sum II", "diff": "medium", "topics": "DFS (premium)"},
        {"n": 605, "slug": "can-place-flowers", "title": "Can Place Flowers", "diff": "easy", "topics": "Greedy, Array"},
        {"n": 53, "slug": "maximum-subarray", "title": "Maximum Subarray", "diff": "medium", "topics": "DP"},
        {"n": 156, "slug": "binary-tree-upside-down", "title": "Binary Tree Upside Down", "diff": "medium", "topics": "Tree (premium)"},
        {"n": 244, "slug": "shortest-word-distance-ii", "title": "Shortest Word Distance II", "diff": "medium", "topics": "Hash Table (premium)"},
        {"n": 380, "slug": "insert-delete-getrandom-o1", "title": "Insert Delete GetRandom O(1)", "diff": "medium", "topics": "Design"},
        {"n": 150, "slug": "evaluate-reverse-polish-notation", "title": "Evaluate Reverse Polish Notation", "diff": "medium", "topics": "Stack"},
        {"n": 432, "slug": "all-oone-data-structure", "title": "All O`one Data Structure", "diff": "hard", "topics": "Design, Linked List"},
        {"n": 297, "slug": "serialize-and-deserialize-binary-tree", "title": "Serialize and Deserialize Binary Tree", "diff": "hard", "topics": "Tree, Design"},
        {"n": 366, "slug": "find-leaves-of-binary-tree", "title": "Find Leaves of Binary Tree", "diff": "medium", "topics": "Tree (premium)"},
        {"n": 254, "slug": "factor-combinations", "title": "Factor Combinations", "diff": "medium", "topics": "Backtracking (premium)"},
    ],
    "Adobe": [
        {"n": 1, "slug": "two-sum", "title": "Two Sum", "diff": "easy", "topics": "Array, Hash Table"},
        {"n": 53, "slug": "maximum-subarray", "title": "Maximum Subarray", "diff": "medium", "topics": "DP"},
        {"n": 121, "slug": "best-time-to-buy-and-sell-stock", "title": "Best Time to Buy and Sell Stock", "diff": "easy", "topics": "DP"},
        {"n": 5, "slug": "longest-palindromic-substring", "title": "Longest Palindromic Substring", "diff": "medium", "topics": "DP, String"},
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph"},
        {"n": 42, "slug": "trapping-rain-water", "title": "Trapping Rain Water", "diff": "hard", "topics": "Two Pointers"},
        {"n": 56, "slug": "merge-intervals", "title": "Merge Intervals", "diff": "medium", "topics": "Sorting"},
        {"n": 79, "slug": "word-search", "title": "Word Search", "diff": "medium", "topics": "Backtracking"},
        {"n": 146, "slug": "lru-cache", "title": "LRU Cache", "diff": "medium", "topics": "Design"},
        {"n": 23, "slug": "merge-k-sorted-lists", "title": "Merge k Sorted Lists", "diff": "hard", "topics": "Heap"},
    ],
    "Goldman Sachs": [
        {"n": 1, "slug": "two-sum", "title": "Two Sum", "diff": "easy", "topics": "Array, Hash Table"},
        {"n": 13, "slug": "roman-to-integer", "title": "Roman to Integer", "diff": "easy", "topics": "Math, String"},
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph"},
        {"n": 53, "slug": "maximum-subarray", "title": "Maximum Subarray", "diff": "medium", "topics": "DP"},
        {"n": 121, "slug": "best-time-to-buy-and-sell-stock", "title": "Best Time to Buy and Sell Stock", "diff": "easy", "topics": "DP"},
        {"n": 387, "slug": "first-unique-character-in-a-string", "title": "First Unique Character in a String", "diff": "easy", "topics": "Hash Table"},
        {"n": 56, "slug": "merge-intervals", "title": "Merge Intervals", "diff": "medium", "topics": "Sorting"},
        {"n": 88, "slug": "merge-sorted-array", "title": "Merge Sorted Array", "diff": "easy", "topics": "Two Pointers"},
        {"n": 49, "slug": "group-anagrams", "title": "Group Anagrams", "diff": "medium", "topics": "Hash Table, String"},
        {"n": 169, "slug": "majority-element", "title": "Majority Element", "diff": "easy", "topics": "Array, Boyer-Moore"},
        {"n": 70, "slug": "climbing-stairs", "title": "Climbing Stairs", "diff": "easy", "topics": "DP"},
        {"n": 146, "slug": "lru-cache", "title": "LRU Cache", "diff": "medium", "topics": "Design"},
    ],
    "Spotify": [
        {"n": 1, "slug": "two-sum", "title": "Two Sum", "diff": "easy", "topics": "Array, Hash Table"},
        {"n": 49, "slug": "group-anagrams", "title": "Group Anagrams", "diff": "medium", "topics": "Hash Table, String"},
        {"n": 200, "slug": "number-of-islands", "title": "Number of Islands", "diff": "medium", "topics": "Graph"},
        {"n": 146, "slug": "lru-cache", "title": "LRU Cache", "diff": "medium", "topics": "Design"},
        {"n": 347, "slug": "top-k-frequent-elements", "title": "Top K Frequent Elements", "diff": "medium", "topics": "Heap, Hash Table"},
        {"n": 23, "slug": "merge-k-sorted-lists", "title": "Merge k Sorted Lists", "diff": "hard", "topics": "Heap"},
        {"n": 33, "slug": "search-in-rotated-sorted-array", "title": "Search in Rotated Sorted Array", "diff": "medium", "topics": "Binary Search"},
        {"n": 207, "slug": "course-schedule", "title": "Course Schedule", "diff": "medium", "topics": "Topological Sort"},
        {"n": 253, "slug": "meeting-rooms-ii", "title": "Meeting Rooms II", "diff": "medium", "topics": "Intervals, Heap (premium)"},
        {"n": 5, "slug": "longest-palindromic-substring", "title": "Longest Palindromic Substring", "diff": "medium", "topics": "DP"},
    ],
}
