-- jobsearch initial schema (Postgres)
-- Generated from webapp/db.py:SCHEMA via webapp/pgcompat.sqlite_schema_to_postgres().
-- This is the single-user data model ported to Postgres verbatim. Multi-tenant
-- columns (user_id, users, user_job_fit) arrive in a later migration with auth
-- (see docs/design-hosting.md / docs/design-hosting-progress.md).

CREATE TABLE IF NOT EXISTS jobs (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key             TEXT UNIQUE NOT NULL,
    source          TEXT NOT NULL,
    company         TEXT NOT NULL,
    title           TEXT NOT NULL,
    location        TEXT DEFAULT '',
    url             TEXT DEFAULT '',
    description     TEXT DEFAULT '',
    posted_at       TEXT,
    fit_score       DOUBLE PRECISION,
    rank_score      DOUBLE PRECISION,
    cluster         INTEGER,
    filter_reason   TEXT DEFAULT '',
    validation      TEXT DEFAULT '',
    validation_note TEXT DEFAULT '',
    first_seen_at   TEXT NOT NULL,
    last_seen_at    TEXT NOT NULL,
    is_active       INTEGER NOT NULL DEFAULT 1,
    -- 1 when this job's company is a known startup (in startup_companies); set
    -- by ingest so the dashboard can show only / hide / mix startup jobs.
    is_startup      INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_jobs_company ON jobs(company);
CREATE INDEX IF NOT EXISTS idx_jobs_first_seen ON jobs(first_seen_at);
CREATE INDEX IF NOT EXISTS idx_jobs_startup ON jobs(is_startup);

CREATE TABLE IF NOT EXISTS job_events (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      INTEGER NOT NULL REFERENCES jobs(id),
    event_type  TEXT NOT NULL,      -- inserted | updated | deactivated | reactivated
    payload     TEXT DEFAULT '',    -- JSON: {field: [old, new], ...}
    created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_job_events_job ON job_events(job_id);

CREATE TABLE IF NOT EXISTS applications (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id        INTEGER UNIQUE NOT NULL REFERENCES jobs(id),
    status        TEXT NOT NULL DEFAULT 'not_applied',
    applied_at    TEXT,
    submitted_via TEXT DEFAULT '',
    notes         TEXT DEFAULT '',
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS application_events (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES applications(id),
    status         TEXT NOT NULL,
    detail         TEXT DEFAULT '',
    created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_app_events_app ON application_events(application_id);

CREATE TABLE IF NOT EXISTS profile_fields (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field      TEXT UNIQUE NOT NULL,
    value      TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingested_at   TEXT NOT NULL,
    report_date   TEXT DEFAULT '',
    jobs_inserted INTEGER NOT NULL DEFAULT 0,
    jobs_updated  INTEGER NOT NULL DEFAULT 0,
    jobs_total    INTEGER NOT NULL DEFAULT 0
);

-- --------------------------------------------------- startup company facts ---
-- The "helpful info" the startup pipeline tracks per company (employees,
-- funding stage/amount, investors, notable people, …). Populated by ingest
-- from data/startup_meta.json (written by `discover-startups`) and editable in
-- the UI; user_edited=1 protects manual edits from being clobbered on re-ingest.
-- Keyed by normalized company name so it joins jobs.company across spellings.
CREATE TABLE IF NOT EXISTS startup_companies (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_key       TEXT UNIQUE NOT NULL,
    name              TEXT NOT NULL,
    employees         TEXT DEFAULT '',
    founded           TEXT DEFAULT '',
    batch             TEXT DEFAULT '',
    status            TEXT DEFAULT '',
    stage             TEXT DEFAULT '',
    last_round        TEXT DEFAULT '',
    last_round_amount TEXT DEFAULT '',
    total_raised      TEXT DEFAULT '',
    investors         TEXT DEFAULT '',   -- JSON array
    notable_people    TEXT DEFAULT '',   -- JSON array
    industry          TEXT DEFAULT '',
    tags              TEXT DEFAULT '',   -- JSON array
    location          TEXT DEFAULT '',
    website           TEXT DEFAULT '',
    one_liner         TEXT DEFAULT '',
    description       TEXT DEFAULT '',
    top_company       INTEGER NOT NULL DEFAULT 0,
    is_hiring         INTEGER NOT NULL DEFAULT 0,
    yc_url            TEXT DEFAULT '',
    source            TEXT DEFAULT '',
    notes             TEXT DEFAULT '',
    user_edited       INTEGER NOT NULL DEFAULT 0,
    updated_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_startup_companies_key ON startup_companies(company_key);

-- ------------------------------------------------- email module scaffold ---
CREATE TABLE IF NOT EXISTS email_accounts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider   TEXT NOT NULL,            -- gmail
    address    TEXT NOT NULL,
    status     TEXT NOT NULL DEFAULT 'disconnected',
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS email_messages (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     INTEGER REFERENCES email_accounts(id),
    application_id INTEGER REFERENCES applications(id),
    job_id         INTEGER REFERENCES jobs(id),
    message_id     TEXT UNIQUE,          -- provider message id
    thread_id      TEXT,
    direction      TEXT DEFAULT 'inbound',
    from_addr      TEXT DEFAULT '',
    to_addr        TEXT DEFAULT '',
    subject        TEXT DEFAULT '',
    snippet        TEXT DEFAULT '',
    body           TEXT DEFAULT '',
    sent_at        TEXT,
    ingested_at    TEXT NOT NULL,
    classification TEXT DEFAULT ''       -- confirmation | interview | rejection | other
);
CREATE INDEX IF NOT EXISTS idx_email_app ON email_messages(application_id);

-- --------------------------------------------- referral discovery scaffold ---
-- Candidates are per-company (an employee can refer for any role at their
-- company); per-(candidate, job) scoring lives in referral_matches.
CREATE TABLE IF NOT EXISTS referral_candidates (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company           TEXT NOT NULL,
    name              TEXT NOT NULL,
    headline          TEXT DEFAULT '',
    linkedin_url      TEXT UNIQUE NOT NULL,
    "current_role"    TEXT DEFAULT '',   -- quoted: reserved keyword in Postgres
    current_company   TEXT DEFAULT '',
    location          TEXT DEFAULT '',
    summary           TEXT DEFAULT '',
    raw_json          TEXT DEFAULT '',
    first_seen_at     TEXT NOT NULL,
    last_refreshed_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_referral_candidates_company ON referral_candidates(company);

CREATE TABLE IF NOT EXISTS referral_matches (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id   INTEGER NOT NULL REFERENCES referral_candidates(id),
    job_id         INTEGER NOT NULL REFERENCES jobs(id),
    job_match      DOUBLE PRECISION NOT NULL DEFAULT 0,
    user_match     DOUBLE PRECISION NOT NULL DEFAULT 0,
    combined       DOUBLE PRECISION NOT NULL DEFAULT 0,
    matched_at     TEXT NOT NULL,
    UNIQUE(candidate_id, job_id)
);
CREATE INDEX IF NOT EXISTS idx_referral_matches_job ON referral_matches(job_id);

-- Per-job discovery state, polled by the UI while a search runs.
CREATE TABLE IF NOT EXISTS referral_runs (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id        INTEGER NOT NULL REFERENCES jobs(id),
    state         TEXT NOT NULL,         -- queued | running | done | error
    detail        TEXT DEFAULT '',
    started_at    TEXT NOT NULL,
    finished_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_referral_runs_job ON referral_runs(job_id);

-- ----------------------------------------- software interview prep modules ---
-- Content is authored in jobsearch/prep/ (coding.py, system_design.py,
-- distributed_systems.py -> ALL_TRACKS) and seeded by jobsearch.prep.seed on
-- every UI start (idempotent — a content_hash in prep_meta detects changes).
-- Progress tables (prep_lesson_progress, prep_problem_progress) are written
-- by the UI as the user works through modules and never wiped by a reseed.
CREATE TABLE IF NOT EXISTS prep_tracks (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    title       TEXT NOT NULL,
    description TEXT DEFAULT '',
    sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS prep_modules (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id     INTEGER NOT NULL REFERENCES prep_tracks(id),
    slug         TEXT UNIQUE NOT NULL,
    title        TEXT NOT NULL,
    summary      TEXT DEFAULT '',
    source_refs  TEXT DEFAULT '',
    est_minutes  INTEGER NOT NULL DEFAULT 30,
    sort_order   INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_prep_modules_track ON prep_modules(track_id);

CREATE TABLE IF NOT EXISTS prep_lessons (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id      INTEGER NOT NULL REFERENCES prep_modules(id),
    slug           TEXT NOT NULL,
    title          TEXT NOT NULL,
    body_md        TEXT NOT NULL,
    source_refs    TEXT DEFAULT '',
    key_takeaways  TEXT DEFAULT '',          -- JSON array of bullet strings
    sort_order     INTEGER NOT NULL DEFAULT 0,
    UNIQUE(module_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_prep_lessons_module ON prep_lessons(module_id);

CREATE TABLE IF NOT EXISTS prep_problems (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id        INTEGER REFERENCES prep_modules(id),
    leetcode_number  INTEGER,
    leetcode_slug    TEXT,
    title            TEXT NOT NULL,
    difficulty       TEXT NOT NULL,          -- easy | medium | hard
    topic            TEXT DEFAULT '',
    url              TEXT DEFAULT '',
    sort_order       INTEGER NOT NULL DEFAULT 0,
    UNIQUE(module_id, leetcode_slug)
);
CREATE INDEX IF NOT EXISTS idx_prep_problems_module ON prep_problems(module_id);

CREATE TABLE IF NOT EXISTS prep_lesson_progress (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id    INTEGER UNIQUE NOT NULL REFERENCES prep_lessons(id),
    state        TEXT NOT NULL DEFAULT 'not_started',
    notes        TEXT DEFAULT '',
    started_at   TEXT,
    completed_at TEXT,
    updated_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS prep_problem_progress (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id   INTEGER UNIQUE NOT NULL REFERENCES prep_problems(id),
    state        TEXT NOT NULL DEFAULT 'not_started',  -- not_started | attempted | solved
    notes        TEXT DEFAULT '',
    solved_at    TEXT,
    updated_at   TEXT NOT NULL
);

-- CtCI book problems (Ch.1-17 of "Cracking the Coding Interview"). Unlike
-- prep_problems (a LeetCode bookmark registry) these carry the full prompt,
-- worked solution, and hint texts from the book itself.
CREATE TABLE IF NOT EXISTS prep_ctci_problems (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id    INTEGER NOT NULL REFERENCES prep_modules(id),
    slug         TEXT NOT NULL,
    ctci_id      TEXT NOT NULL,                       -- e.g. "1.1", "16.4"
    title        TEXT NOT NULL,
    prompt_md    TEXT NOT NULL,
    examples_md  TEXT DEFAULT '',
    hints        TEXT DEFAULT '',                     -- JSON array of strings
    solution_md  TEXT NOT NULL,
    complexity   TEXT DEFAULT '',
    sort_order   INTEGER NOT NULL DEFAULT 0,
    UNIQUE(module_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_prep_ctci_problems_module ON prep_ctci_problems(module_id);

CREATE TABLE IF NOT EXISTS prep_ctci_problem_progress (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ctci_problem_id INTEGER UNIQUE NOT NULL REFERENCES prep_ctci_problems(id),
    state           TEXT NOT NULL DEFAULT 'not_started',
    notes           TEXT DEFAULT '',
    solved_at       TEXT,
    updated_at      TEXT NOT NULL
);

-- Stamped after a successful seed so reseeds skip work when content unchanged.
CREATE TABLE IF NOT EXISTS prep_meta (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- ------------------------------------- company-specific LeetCode questions ---
-- "What does <company> actually ask?" — one row per (company, problem).
-- Seeded from the bundled curated set (jobsearch/company_questions) on every
-- UI start, and refreshed/extended from a community dataset via the
-- "⟳ Refresh questions" button. Solve/attempt progress lives in a separate
-- table keyed by row id, so re-seeding or refreshing never wipes it.
CREATE TABLE IF NOT EXISTS company_problems (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company           TEXT NOT NULL,            -- display name ("Goldman Sachs")
    company_key       TEXT NOT NULL,            -- normalized match key ("goldman sachs")
    leetcode_number   INTEGER,
    leetcode_slug     TEXT NOT NULL,
    title             TEXT NOT NULL,
    difficulty        TEXT NOT NULL DEFAULT 'medium',  -- easy | medium | hard
    frequency         DOUBLE PRECISION NOT NULL DEFAULT 0,  -- 0–100; how often this company asks it
    timeframe         TEXT DEFAULT '',          -- curated | alltime | 6months | ...
    topics            TEXT DEFAULT '',
    url               TEXT DEFAULT '',
    source            TEXT DEFAULT 'bundled',   -- bundled | github_csv | ...
    first_seen_at     TEXT NOT NULL,
    last_refreshed_at TEXT NOT NULL,
    UNIQUE(company_key, leetcode_slug)
);
CREATE INDEX IF NOT EXISTS idx_company_problems_key ON company_problems(company_key);

CREATE TABLE IF NOT EXISTS company_problem_progress (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_problem_id INTEGER UNIQUE NOT NULL REFERENCES company_problems(id),
    state              TEXT NOT NULL DEFAULT 'not_started',  -- not_started | attempted | solved
    notes              TEXT DEFAULT '',
    solved_at          TEXT,
    updated_at         TEXT NOT NULL
);

-- Per-company (or all-company) refresh state, polled by the UI while a
-- background pull runs — mirrors referral_runs.
CREATE TABLE IF NOT EXISTS company_refresh_runs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_key TEXT DEFAULT '',         -- '' = all companies
    state       TEXT NOT NULL,           -- running | done | error
    detail      TEXT DEFAULT '',
    added       INTEGER NOT NULL DEFAULT 0,
    updated     INTEGER NOT NULL DEFAULT 0,
    started_at  TEXT NOT NULL,
    finished_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_company_refresh_key ON company_refresh_runs(company_key);
