-- Company registry (Stage 1): the per-user, per-track set of companies the
-- pipeline searches, previously only in the gitignored YAML registries. Mirrors
-- the `companies` + `company_search_runs` tables in webapp/db.py:SCHEMA so the
-- local SQLite schema and the hosted Postgres schema stay in lockstep. `user_id`
-- is carried from day one (defaulting to the local owner) so the multi-tenancy
-- migration adds no column here. Search-state (last_searched_at, last_found_jobs)
-- feeds fresh, not-recently-searched discovery in a later stage.

CREATE TABLE IF NOT EXISTS companies (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          TEXT NOT NULL DEFAULT 'local',
    track            TEXT NOT NULL DEFAULT 'main',
    company_key      TEXT NOT NULL,
    name             TEXT NOT NULL,
    ats              TEXT NOT NULL DEFAULT '',
    careers_url      TEXT DEFAULT '',
    tags             TEXT DEFAULT '',
    params           TEXT DEFAULT '',
    source           TEXT NOT NULL DEFAULT 'curated',
    discovered_via   TEXT DEFAULT '',
    enabled          INTEGER NOT NULL DEFAULT 1,
    first_seen_at    TEXT NOT NULL,
    last_searched_at TEXT DEFAULT '',
    last_found_jobs  INTEGER NOT NULL DEFAULT 0,
    user_edited      INTEGER NOT NULL DEFAULT 0,
    updated_at       TEXT NOT NULL,
    UNIQUE(user_id, track, company_key)
);
CREATE INDEX IF NOT EXISTS idx_companies_user_track ON companies(user_id, track, enabled);
CREATE INDEX IF NOT EXISTS idx_companies_sweep ON companies(user_id, track, last_searched_at);

CREATE TABLE IF NOT EXISTS company_search_runs (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            TEXT NOT NULL DEFAULT 'local',
    track              TEXT NOT NULL DEFAULT 'main',
    ran_at             TEXT NOT NULL,
    source             TEXT NOT NULL DEFAULT 'ingest',
    companies_total    INTEGER NOT NULL DEFAULT 0,
    companies_new      INTEGER NOT NULL DEFAULT 0,
    companies_disabled INTEGER NOT NULL DEFAULT 0,
    jobs_found         INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_company_search_runs ON company_search_runs(user_id, track, ran_at);
