-- Stage 2b (part 4a): per-user résumé-fit.
-- fit_score/rank_score/cluster were single-user columns on jobs (scored against
-- one résumé). This adds a per-user overlay so each account sees its own matches
-- (each user's résumé vs the job corpus). The dashboard reads fit through this
-- table LEFT JOINed on the current user; jobs.fit_* stays as the pipeline's
-- (owner) scores for the CLI report and is mirrored into the 'local' rows on
-- ingest so single-user mode is unchanged. New table — additive, no data moves.

CREATE TABLE IF NOT EXISTS user_job_fit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     TEXT NOT NULL DEFAULT 'local',
    job_id      BIGINT NOT NULL REFERENCES jobs(id),
    fit_score   DOUBLE PRECISION,
    rank_score  DOUBLE PRECISION,
    cluster     INTEGER,
    updated_at  TEXT NOT NULL,
    UNIQUE(user_id, job_id)
);
CREATE INDEX IF NOT EXISTS idx_user_job_fit_user ON user_job_fit(user_id);
