"""Postgres backend for the webapp data layer.

The app was built single-user on SQLite (see ``db.py``). Taking it online for
multi-device, multi-user access (``docs/design-hosting.md``) means the same
code has to run against managed Postgres — Supabase, in this project.

Rather than rewrite the ~130 hand-written SQL sites, this module adapts a
``psycopg`` (v3) connection to the small slice of the ``sqlite3.Connection``
API the codebase actually uses:

  * ``conn.execute(sql, params)`` returning a cursor with ``fetchone`` /
    ``fetchall`` / ``rowcount``
  * ``conn.executescript(schema)`` to create tables on first connect
  * ``conn.commit()`` / ``conn.rollback()`` / ``conn.close()``
  * dict-style rows (``row["col"]``) — the codebase never indexes columns
    positionally, so ``dict_row`` is a faithful stand-in for ``sqlite3.Row``

It also translates the two placeholder styles SQLite uses (``?`` and
``:name``) into psycopg's (``%s`` and ``%(name)s``), and the handful of DDL
constructs that differ between the dialects.

This backend is selected by :func:`webapp.db.connect` only when
``JOBSEARCH_DATABASE_URL`` is set. Local development and the test suite stay on
SQLite and are completely unaffected by this file.
"""

from __future__ import annotations

import re

_NAMED = re.compile(r":(\w+)")


def translate_query(sql: str, params):
    """Translate a SQLite query + params into the psycopg equivalent.

    * No params → passed through verbatim (psycopg does no ``%`` interpolation
      when ``params`` is ``None``, so literal ``%`` stays literal).
    * Dict params → ``:name`` becomes ``%(name)s`` (named placeholders).
    * Sequence params → ``?`` becomes ``%s`` (positional placeholders).

    When params are present any literal ``%`` is doubled to ``%%`` first, so a
    ``LIKE '%x%'`` written directly in SQL would survive — though in this
    codebase the wildcards live in the *values*, not the SQL text.
    """
    if not params:
        return sql, None
    sql = sql.replace("%", "%%")
    if isinstance(params, dict):
        return _NAMED.sub(r"%(\1)s", sql), params
    return sql.replace("?", "%s"), list(params)


def sqlite_schema_to_postgres(schema: str) -> str:
    """Translate the SQLite DDL in :data:`webapp.db.SCHEMA` to Postgres.

    Only two constructs in our schema differ between the dialects:

    * ``INTEGER PRIMARY KEY`` — SQLite's implicit auto-incrementing rowid —
      becomes ``INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`` (the
      modern Postgres equivalent; ``BY DEFAULT`` still allows explicit-id
      inserts should any caller need them).
    * ``REAL`` — 8-byte float in SQLite but only 4-byte in Postgres — becomes
      ``DOUBLE PRECISION`` so fit/rank scores keep full precision.

    Everything else (``TEXT``, ``INTEGER``, ``UNIQUE``, ``REFERENCES``,
    ``CREATE TABLE/INDEX IF NOT EXISTS`` …) is already valid Postgres.
    """
    schema = re.sub(
        r"\bINTEGER PRIMARY KEY\b",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        schema,
    )
    schema = re.sub(r"\bREAL\b", "DOUBLE PRECISION", schema)
    return schema


def _split_statements(script: str) -> list[str]:
    """Split a DDL script into individual statements for psycopg.

    psycopg's extended protocol runs one command per ``execute`` call, so the
    schema (a single ``;``-separated string) has to be split. ``--`` line
    comments are stripped first: the schema documents columns with notes, some
    of which contain ``;`` (e.g. ``"…(in startup_companies); set …"``) that
    would otherwise split a statement mid-stream. Neither ``--`` nor ``;``
    appears inside a string literal in this schema, so this is safe.
    """
    no_comments = "\n".join(line.split("--", 1)[0] for line in script.splitlines())
    return [stmt.strip() for stmt in no_comments.split(";") if stmt.strip()]


class PgConnection:
    """A thin ``sqlite3.Connection``-compatible adapter over psycopg.

    Wraps a live :class:`psycopg.Connection` and intercepts ``execute`` to
    translate placeholders. Anything not wrapped here (``cursor``, transaction
    context managers, …) is delegated to the underlying connection.
    """

    def __init__(self, pg) -> None:
        self._pg = pg

    def execute(self, sql: str, params=()):
        query, translated = translate_query(sql, params)
        return self._pg.execute(query, translated)

    def executescript(self, script: str) -> "PgConnection":
        for statement in _split_statements(script):
            self._pg.execute(statement)
        self._pg.commit()
        return self

    def commit(self) -> None:
        self._pg.commit()

    def rollback(self) -> None:
        self._pg.rollback()

    def close(self) -> None:
        self._pg.close()

    def __getattr__(self, name):
        # Delegate the rest of the sqlite3.Connection surface to psycopg.
        return getattr(self._pg, name)


def connect_postgres(url: str) -> PgConnection:
    """Open a Postgres connection adapted to the SQLite-shaped DB API.

    Imports psycopg lazily so the dependency is only required when actually
    running against Postgres (hosted deployments), not for local SQLite use.
    """
    import psycopg
    from psycopg.rows import dict_row

    pg = psycopg.connect(url, row_factory=dict_row, autocommit=False)
    return PgConnection(pg)
